spring.jpa.show-sql=false
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=update
jwt.secret=lorem98ufsdoijr98jiojsdfu984we89Ujkol33f
jwt.expiration=600000

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

#spring.datasource.url=jdbc:h2:mem:gestioneventosdb
spring.datasource.url=jdbc:postgresql://ep-icy-rice-an81gr05-pooler.c-6.us-east-1.aws.neon.tech/cefiretlx?sslmode=require&channelBinding=require
#spring.datasource.username=sa neondb_owner
spring.datasource.username=neondb_owner
#spring.datasource.password=admin1234 npg_PBnoZQLj5ui1
spring.datasource.password=npg_PBnoZQLj5ui1
#spring.datasource.driverClassName=org.h2.Driver
spring.datasource.driverClassName=org.postgresql.Driver
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
